name: "Build Juliet projects"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build projects separately
      run: |
        find * -type f -name "*.csproj" | \
          xargs -n 1 bash -c 'dotnet build $0 || exit 255'
